global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'bot'
    static_configs:
      - targets: ['host.docker.internal:8001']
  - job_name: 'database'
    static_configs:
      - targets: ['host.docker.internal:8010']