"""empty message

Revision ID: 188a09cc96fa
Revises: 495fed328af2
Create Date: 2024-11-28 20:10:30.035822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188a09cc96fa'
down_revision: Union[str, None] = '495fed328af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=250), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memes')),
    schema='public'
    )
    op.create_index(op.f('ix_public_memes_user_id'), 'memes', ['user_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_memes_user_id'), table_name='memes', schema='public')
    op.drop_table('memes', schema='public')
    # ### end Alembic commands ###
