"""Add nullable description

Revision ID: 761a2a6a86b3
Revises: f158b8fba192
Create Date: 2024-11-30 06:50:26.544871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761a2a6a86b3'
down_revision: Union[str, None] = 'f158b8fba192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memes', 'description',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_constraint('fk_ratings_meme_id_memes', 'ratings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ratings_meme_id_memes'), 'ratings', 'memes', ['meme_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('fk_saved_meme_id_memes', 'saved', type_='foreignkey')
    op.create_foreign_key(op.f('fk_saved_meme_id_memes'), 'saved', 'memes', ['meme_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_saved_meme_id_memes'), 'saved', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_saved_meme_id_memes', 'saved', 'memes', ['meme_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_ratings_meme_id_memes'), 'ratings', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_ratings_meme_id_memes', 'ratings', 'memes', ['meme_id'], ['id'], ondelete='CASCADE')
    op.alter_column('memes', 'description',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
