"""Init

Revision ID: f158b8fba192
Revises: 
Create Date: 2024-11-30 02:29:19.940816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f158b8fba192'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memes',
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memes')),
    schema='public'
    )
    op.create_index(op.f('ix_public_memes_creator_id'), 'memes', ['creator_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_memes_is_public'), 'memes', ['is_public'], unique=False, schema='public')
    op.create_table('ratings',
    sa.Column('meme_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meme_id'], ['public.memes.id'], name=op.f('fk_ratings_meme_id_memes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings')),
    sa.UniqueConstraint('meme_id', 'user_id', name='uq_ratings_meme_user'),
    schema='public'
    )
    op.create_index('ix_ratings_meme_id_is_like', 'ratings', ['meme_id', 'is_like'], unique=False, schema='public')
    op.create_index('ix_ratings_meme_id_user_id', 'ratings', ['meme_id', 'user_id'], unique=False, schema='public')
    op.create_table('saved',
    sa.Column('meme_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meme_id'], ['public.memes.id'], name=op.f('fk_saved_meme_id_memes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved')),
    sa.UniqueConstraint('meme_id', 'user_id', name='uq_saved_meme_user'),
    schema='public'
    )
    op.create_index(op.f('ix_public_saved_user_id'), 'saved', ['user_id'], unique=False, schema='public')
    op.create_index('ix_saved_meme_id_user_id', 'saved', ['meme_id', 'user_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_meme_id_user_id', table_name='saved', schema='public')
    op.drop_index(op.f('ix_public_saved_user_id'), table_name='saved', schema='public')
    op.drop_table('saved', schema='public')
    op.drop_index('ix_ratings_meme_id_user_id', table_name='ratings', schema='public')
    op.drop_index('ix_ratings_meme_id_is_like', table_name='ratings', schema='public')
    op.drop_table('ratings', schema='public')
    op.drop_index(op.f('ix_public_memes_is_public'), table_name='memes', schema='public')
    op.drop_index(op.f('ix_public_memes_creator_id'), table_name='memes', schema='public')
    op.drop_table('memes', schema='public')
    # ### end Alembic commands ###
